### ISSUE TITLE
Create Project Task List for Discussion

### ISSUE THREAD

**Issue by VernonNaidoo-Toronto** [CommonSenseMachineLearning/OntarioPower#3]
Create a high-level list of 5-10 tasks for this project (creating a basic ML model).  **Do it without looking at any references.**  Just think about it.  It will help us both to see what you know and what you don't know.  It doesn't have to be correct. Write up the way you think it should work.  We will discuss and modify when you are finished.  (There is no right answer.)  
- [x] Create a list of ~5 - 10 tasks.
- [x] Attach to this card (or create a new card).
- [x] Get feedback (from me).
